hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - model_params/199@model_params.199
  - model_params/300@model_params.300
  - model_params/400@model_params.400
  - _self_

local_paths:
  raw: data/raw/sample.csv
  processed: data/processed/processed.csv
  final: data/final/final.csv

main_params:
  timeout: 600
  fpr_max: 0.05
  metric: precision
  seed: 1968


    



